#!/bin/bash

INPUT=$1
OUTPUT=$2

TEMPDIR=`mktemp -d`

# input info
INFO="$TEMPDIR/ffprobe.txt"

# demux output
DEMUX_H264="$TEMPDIR/video.h264"
DEMUX_AUDIOSUB="$TEMPDIR/audiosub.ts"

# ldecod output
LDECOD_OUTPUT="$TEMPDIR/dec.yuv"
YUV_LEFT="$TEMPDIR/dec_ViewId0000.yuv"
YUV_RIGHT="$TEMPDIR/dec_ViewId0001.yuv"

# Side By Side pipe output
YUV_SBS="$TEMPDIR/sbs.yuv"


# gather information about input
ffprobe $INPUT 2>&1 | grep "Stream #0" > $INFO
FRAMERATE=`cat $INFO|grep "Video:"| grep "Video:"|cut -d',' -f4|tr -d " fps"`
RES=`cat $INFO|grep "Video:"| grep "Video:"|cut -d',' -f3|cut -d' ' -f2`
NSUB=`cat $INFO|grep -c "Subtitle"`

# filter input information
RES_X=`echo $RES|cut -d'x' -f1`
RES_Y=`echo $RES|cut -d'x' -f2`
let DRES_X=2*$RES_X
let DRES_Y=2*$RES_Y
[ "$FRAMERATE" = "23.98" ] && FRAMERATE="24000/1001"

echo "FRAMERATE=$FRAMERATE"
echo "NSUB=$NSUB"
echo "RES=$RES_X,$RES_Y"
echo "SBS RES=$DRES_X,$RES_Y"

# generate subtile muxing options if there are subtitles
MAPSUB0="-map 0:s"
MAPSUB1="-map 1:s"
CODECSUB="-c:s copy"
if [ $NSUB -lt 1 ]
then
	echo "No subtitles"
	MAPSUB0=""
	MAPSUB1=""
	CODECSUB=""
fi

# Create pipes
set -x
mkfifo $DEMUX_H264 $YUV_LEFT $YUV_RIGHT $YUV_SBS $DEMUX_AUDIOSUB

# extract raw H.264+MVC track with AnnexB flavour
# -map 0:a -c:a copy $DEMUX_AUDIOSUB &
ffmpeg -v 0 -y -i $INPUT -map 0:v -f h264 -c:v copy -bsf:v h264_mp4toannexb $DEMUX_H264 &
sleep 2

# decode H.264+MVC stream using Franhauffer JM 18.6 soft
#LDECOD_DBG="-p DecFrmNum=120"
ldecod.exe -d /usr/local/etc/decoder.cfg -p DecodeAllLayers=1 -p InputFile=$DEMUX_H264 -p OutputFile=$LDECOD_OUTPUT -p Silent=1 $LDECOD_DBG &
sleep 2

# bufferize 2 inputs and output a single Side By Side raw YUV420p stream
yuvsbspipe -w $RES_X -h $RES_Y -n 48 -l $YUV_LEFT -r $YUV_RIGHT -sbs -o $YUV_SBS &
sleep 2

ffmpeg -y -f rawvideo -pixel_format yuv420p -video_size $ -framerate $FRAMERATE -i $YUV_SBS \
	-map 0:v \
	-vf scale=iw/2,-1 \
	-c:v libx264 -preset:v veryslow -crf:v 20 -bluray-compat:v 1 \
	$OUTPUT
#	-i $INPUT \
#	-map 1:a \

rm -fr $TEMPDIR

